BENCHMARK = $(shell basename `pwd`)
EXECUTABLE := $(BENCHMARK)-cuda.exe
CUFILES := $(BENCHMARK).cu
PATH_TO_UTILS := ../../utilities
CXX := g++-4.8
OPT_LEVEL := -O3
NVCC := nvcc

include ${PATH_TO_UTILS}/common.mk
