all:
	${NVCC} ${OPT_LEVEL} ${CUFILES} -I${PATH_TO_UTILS} ${INCLUDE_DIR} ${POLYBENCH_OPTIONS} -ccbin=${CXX} -o ${EXECUTABLE}
clean:
	rm -f *~ *.exe

info:
	@echo "Use:"
	@echo "make POLYBENCH_OPTIONS=\"-DPOLYBENCH_TIME -DTOY_DATASET -DRUN_ORIG_VERSION\""
	@echo "make POLYBENCH_OPTIONS=\"-DPOLYBENCH_TIME -DMINI_DATASET -DRUN_ORIG_VERSION\""
	@echo "make POLYBENCH_OPTIONS=\"-DPOLYBENCH_TIME -DTINY_DATASET -DRUN_ORIG_VERSION\""
	@echo "make POLYBENCH_OPTIONS=\"-DPOLYBENCH_TIME -DSMALL_DATASET -DRUN_ORIG_VERSION\""
	@echo "make POLYBENCH_OPTIONS=\"-DPOLYBENCH_TIME -DMEDIUM_DATASET -DRUN_ORIG_VERSION\""
	@echo "make POLYBENCH_OPTIONS=\"-DPOLYBENCH_TIME -DSTANDARD_DATASET -DRUN_ORIG_VERSION\""
	@echo "make POLYBENCH_OPTIONS=\"-DPOLYBENCH_TIME -DLARGE_DATASET -DRUN_ORIG_VERSION\""
	@echo "make POLYBENCH_OPTIONS=\"-DPOLYBENCH_TIME -DEXTRALARGE_DATASET -DRUN_ORIG_VERSION\""
	@echo "make POLYBENCH_OPTIONS=\"-DPOLYBENCH_TIME -DHUGE_DATASET -DRUN_ORIG_VERSION\""
	@echo "use the option -DRUN_ORIG_VERSION to run the sequential version."
	@echo "TOY_DATASET: 32, MINI_DATASET: 64, TINY_DATASET: 128, SMALL_DATASET: 256, MEDIUM_DATASET: 512, STANDARD_DATASET: 1024, LARGE_DATASET: 2048, EXTRALARGE_DATASET: 4096, HUGE_DATASET: 8192"
 
