BENCHMARK  := $(shell basename `pwd`)
OBJFILE := ${BENCHMARK}-offloading-gpu.o
EXECUTABLE := ${BENCHMARK}-offloading-gpu.exe
CUFILES := ${BENCHMARK}.cu
PATH_TO_UTILS := ../../../utilities
CXX := g++-4.8
OPT_LEVEL := -O0

include ${PATH_TO_UTILS}/common.mk